//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/iSync.EAI.DTO")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.datacontract.org/2004/07/iSync.EAI.DTO", IsNullable=true)]
public partial class SalesOrder {
    
    private string commentsField;
    
    private int createdByIDField;
    
    private bool createdByIDFieldSpecified;
    
    private System.DateTime createdDateField;
    
    private bool createdDateFieldSpecified;
    
    private System.Nullable<int> customerIDField;
    
    private bool customerIDFieldSpecified;
    
    private string customerNameField;
    
    private AddressDetail deliveryDetailField;
    
    private System.Nullable<bool> isRejectField;
    
    private bool isRejectFieldSpecified;
    
    private System.Nullable<bool> isXStockField;
    
    private bool isXStockFieldSpecified;
    
    private SalesOrderDetail[] lineItemsField;
    
    private string orderNumberField;
    
    private string pONumberField;
    
    private System.Nullable<System.DateTime> requiredDateField;
    
    private bool requiredDateFieldSpecified;
    
    private int salesOrderIDField;
    
    private bool salesOrderIDFieldSpecified;
    
    private System.Nullable<int> salesRepIDField;
    
    private bool salesRepIDFieldSpecified;
    
    private string specialInstructionsField;
    
    private System.Nullable<int> statusIDField;
    
    private bool statusIDFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Comments {
        get {
            return this.commentsField;
        }
        set {
            this.commentsField = value;
        }
    }
    
    /// <remarks/>
    public int CreatedByID {
        get {
            return this.createdByIDField;
        }
        set {
            this.createdByIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool CreatedByIDSpecified {
        get {
            return this.createdByIDFieldSpecified;
        }
        set {
            this.createdByIDFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime CreatedDate {
        get {
            return this.createdDateField;
        }
        set {
            this.createdDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool CreatedDateSpecified {
        get {
            return this.createdDateFieldSpecified;
        }
        set {
            this.createdDateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<int> CustomerID {
        get {
            return this.customerIDField;
        }
        set {
            this.customerIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool CustomerIDSpecified {
        get {
            return this.customerIDFieldSpecified;
        }
        set {
            this.customerIDFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string CustomerName {
        get {
            return this.customerNameField;
        }
        set {
            this.customerNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public AddressDetail DeliveryDetail {
        get {
            return this.deliveryDetailField;
        }
        set {
            this.deliveryDetailField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<bool> IsReject {
        get {
            return this.isRejectField;
        }
        set {
            this.isRejectField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool IsRejectSpecified {
        get {
            return this.isRejectFieldSpecified;
        }
        set {
            this.isRejectFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<bool> IsXStock {
        get {
            return this.isXStockField;
        }
        set {
            this.isXStockField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool IsXStockSpecified {
        get {
            return this.isXStockFieldSpecified;
        }
        set {
            this.isXStockFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
    public SalesOrderDetail[] LineItems {
        get {
            return this.lineItemsField;
        }
        set {
            this.lineItemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string OrderNumber {
        get {
            return this.orderNumberField;
        }
        set {
            this.orderNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string PONumber {
        get {
            return this.pONumberField;
        }
        set {
            this.pONumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<System.DateTime> RequiredDate {
        get {
            return this.requiredDateField;
        }
        set {
            this.requiredDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool RequiredDateSpecified {
        get {
            return this.requiredDateFieldSpecified;
        }
        set {
            this.requiredDateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public int SalesOrderID {
        get {
            return this.salesOrderIDField;
        }
        set {
            this.salesOrderIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool SalesOrderIDSpecified {
        get {
            return this.salesOrderIDFieldSpecified;
        }
        set {
            this.salesOrderIDFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<int> SalesRepID {
        get {
            return this.salesRepIDField;
        }
        set {
            this.salesRepIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool SalesRepIDSpecified {
        get {
            return this.salesRepIDFieldSpecified;
        }
        set {
            this.salesRepIDFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string SpecialInstructions {
        get {
            return this.specialInstructionsField;
        }
        set {
            this.specialInstructionsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<int> StatusID {
        get {
            return this.statusIDField;
        }
        set {
            this.statusIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool StatusIDSpecified {
        get {
            return this.statusIDFieldSpecified;
        }
        set {
            this.statusIDFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/iSync.EAI.DTO")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.datacontract.org/2004/07/iSync.EAI.DTO", IsNullable=true)]
public partial class AddressDetail {
    
    private int addressDetailIDField;
    
    private bool addressDetailIDFieldSpecified;
    
    private string addressLine1Field;
    
    private string addressLine2Field;
    
    private string altNumberField;
    
    private string cityField;
    
    private string companyField;
    
    private string countryField;
    
    private string emailField;
    
    private string fullNameField;
    
    private string mobileField;
    
    private string phoneField;
    
    private string postCodeField;
    
    private string provinceField;
    
    /// <remarks/>
    public int AddressDetailID {
        get {
            return this.addressDetailIDField;
        }
        set {
            this.addressDetailIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool AddressDetailIDSpecified {
        get {
            return this.addressDetailIDFieldSpecified;
        }
        set {
            this.addressDetailIDFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string AddressLine1 {
        get {
            return this.addressLine1Field;
        }
        set {
            this.addressLine1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string AddressLine2 {
        get {
            return this.addressLine2Field;
        }
        set {
            this.addressLine2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string AltNumber {
        get {
            return this.altNumberField;
        }
        set {
            this.altNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string City {
        get {
            return this.cityField;
        }
        set {
            this.cityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Company {
        get {
            return this.companyField;
        }
        set {
            this.companyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Country {
        get {
            return this.countryField;
        }
        set {
            this.countryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Email {
        get {
            return this.emailField;
        }
        set {
            this.emailField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string FullName {
        get {
            return this.fullNameField;
        }
        set {
            this.fullNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Mobile {
        get {
            return this.mobileField;
        }
        set {
            this.mobileField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Phone {
        get {
            return this.phoneField;
        }
        set {
            this.phoneField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string PostCode {
        get {
            return this.postCodeField;
        }
        set {
            this.postCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Province {
        get {
            return this.provinceField;
        }
        set {
            this.provinceField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/iSync.EAI.DTO")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.datacontract.org/2004/07/iSync.EAI.DTO", IsNullable=true)]
public partial class SalesOrderDetail {
    
    private string commentField;
    
    private System.Nullable<decimal> commissionField;
    
    private bool commissionFieldSpecified;
    
    private System.Nullable<int> commissionIDField;
    
    private bool commissionIDFieldSpecified;
    
    private string descriptionField;
    
    private System.Nullable<decimal> discountField;
    
    private bool discountFieldSpecified;
    
    private System.Nullable<System.DateTime> dueDateField;
    
    private bool dueDateFieldSpecified;
    
    private System.Nullable<decimal> exRateField;
    
    private bool exRateFieldSpecified;
    
    private System.Nullable<int> jobProductIDField;
    
    private bool jobProductIDFieldSpecified;
    
    private System.Nullable<decimal> rateField;
    
    private bool rateFieldSpecified;
    
    private string referenceField;
    
    private System.Nullable<int> repCodeIDField;
    
    private bool repCodeIDFieldSpecified;
    
    private int sODetailIDField;
    
    private bool sODetailIDFieldSpecified;
    
    private System.Nullable<decimal> sellingPriceField;
    
    private bool sellingPriceFieldSpecified;
    
    private SkuDetail[] skuDetailsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Comment {
        get {
            return this.commentField;
        }
        set {
            this.commentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<decimal> Commission {
        get {
            return this.commissionField;
        }
        set {
            this.commissionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool CommissionSpecified {
        get {
            return this.commissionFieldSpecified;
        }
        set {
            this.commissionFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<int> CommissionID {
        get {
            return this.commissionIDField;
        }
        set {
            this.commissionIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool CommissionIDSpecified {
        get {
            return this.commissionIDFieldSpecified;
        }
        set {
            this.commissionIDFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<decimal> Discount {
        get {
            return this.discountField;
        }
        set {
            this.discountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool DiscountSpecified {
        get {
            return this.discountFieldSpecified;
        }
        set {
            this.discountFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<System.DateTime> DueDate {
        get {
            return this.dueDateField;
        }
        set {
            this.dueDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool DueDateSpecified {
        get {
            return this.dueDateFieldSpecified;
        }
        set {
            this.dueDateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<decimal> ExRate {
        get {
            return this.exRateField;
        }
        set {
            this.exRateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ExRateSpecified {
        get {
            return this.exRateFieldSpecified;
        }
        set {
            this.exRateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<int> JobProductID {
        get {
            return this.jobProductIDField;
        }
        set {
            this.jobProductIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool JobProductIDSpecified {
        get {
            return this.jobProductIDFieldSpecified;
        }
        set {
            this.jobProductIDFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<decimal> Rate {
        get {
            return this.rateField;
        }
        set {
            this.rateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool RateSpecified {
        get {
            return this.rateFieldSpecified;
        }
        set {
            this.rateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Reference {
        get {
            return this.referenceField;
        }
        set {
            this.referenceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<int> RepCodeID {
        get {
            return this.repCodeIDField;
        }
        set {
            this.repCodeIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool RepCodeIDSpecified {
        get {
            return this.repCodeIDFieldSpecified;
        }
        set {
            this.repCodeIDFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public int SODetailID {
        get {
            return this.sODetailIDField;
        }
        set {
            this.sODetailIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool SODetailIDSpecified {
        get {
            return this.sODetailIDFieldSpecified;
        }
        set {
            this.sODetailIDFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<decimal> SellingPrice {
        get {
            return this.sellingPriceField;
        }
        set {
            this.sellingPriceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool SellingPriceSpecified {
        get {
            return this.sellingPriceFieldSpecified;
        }
        set {
            this.sellingPriceFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
    public SkuDetail[] SkuDetails {
        get {
            return this.skuDetailsField;
        }
        set {
            this.skuDetailsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/iSync.EAI.DTO")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.datacontract.org/2004/07/iSync.EAI.DTO", IsNullable=true)]
public partial class SkuDetail {
    
    private int productStockIDField;
    
    private bool productStockIDFieldSpecified;
    
    private string sizeField;
    
    private int sizeIDField;
    
    private bool sizeIDFieldSpecified;
    
    private int sizeIndexField;
    
    private bool sizeIndexFieldSpecified;
    
    private string thirdPartyBarcodeField;
    
    private int unitsField;
    
    private bool unitsFieldSpecified;
    
    /// <remarks/>
    public int ProductStockID {
        get {
            return this.productStockIDField;
        }
        set {
            this.productStockIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ProductStockIDSpecified {
        get {
            return this.productStockIDFieldSpecified;
        }
        set {
            this.productStockIDFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Size {
        get {
            return this.sizeField;
        }
        set {
            this.sizeField = value;
        }
    }
    
    /// <remarks/>
    public int SizeID {
        get {
            return this.sizeIDField;
        }
        set {
            this.sizeIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool SizeIDSpecified {
        get {
            return this.sizeIDFieldSpecified;
        }
        set {
            this.sizeIDFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public int SizeIndex {
        get {
            return this.sizeIndexField;
        }
        set {
            this.sizeIndexField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool SizeIndexSpecified {
        get {
            return this.sizeIndexFieldSpecified;
        }
        set {
            this.sizeIndexFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string ThirdPartyBarcode {
        get {
            return this.thirdPartyBarcodeField;
        }
        set {
            this.thirdPartyBarcodeField = value;
        }
    }
    
    /// <remarks/>
    public int Units {
        get {
            return this.unitsField;
        }
        set {
            this.unitsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool UnitsSpecified {
        get {
            return this.unitsFieldSpecified;
        }
        set {
            this.unitsFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/iSync.EAI.DTO")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.datacontract.org/2004/07/iSync.EAI.DTO", IsNullable=true)]
public partial class ArrayOfSalesOrderDetail {
    
    private SalesOrderDetail[] salesOrderDetailField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("SalesOrderDetail", IsNullable=true)]
    public SalesOrderDetail[] SalesOrderDetail {
        get {
            return this.salesOrderDetailField;
        }
        set {
            this.salesOrderDetailField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/iSync.EAI.DTO")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.datacontract.org/2004/07/iSync.EAI.DTO", IsNullable=true)]
public partial class ArrayOfSkuDetail {
    
    private SkuDetail[] skuDetailField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("SkuDetail", IsNullable=true)]
    public SkuDetail[] SkuDetail {
        get {
            return this.skuDetailField;
        }
        set {
            this.skuDetailField = value;
        }
    }
}
