//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Softserve_Chat_SignalR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblChatMessages
    {
        public int iChatMessageID { get; set; }
        public int iUserID { get; set; }
        public int iChatLogID { get; set; }
        public string strMessage { get; set; }
        public bool bIsDeleted { get; set; }
    
        public virtual tblChatLog tblChatLog { get; set; }
        public virtual tblUser tblUser { get; set; }
    }
}
