//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Softserve_Chat_SignalR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblChatLog
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblChatLog()
        {
            this.tblChatMessages = new HashSet<tblChatMessage>();
        }
    
        public int iChatLogID { get; set; }
        public System.DateTime dtAdded { get; set; }
        public int iAddedBy { get; set; }
        public Nullable<System.DateTime> dtEdited { get; set; }
        public Nullable<int> iEditedBy { get; set; }
        public int iUserID { get; set; }
        public string strFirstName { get; set; }
        public string strSurname { get; set; }
        public string strEmailAddress { get; set; }
        public string strContactNumber { get; set; }
        public System.DateTime dtEndOfChat { get; set; }
        public string strRef { get; set; }
        public int iReasonForChatID { get; set; }
        public int iStatusID { get; set; }
        public bool bIsDeleted { get; set; }
    
        public virtual tblReasonForChat tblReasonForChat { get; set; }
        public virtual tblStatus tblStatus { get; set; }
        public virtual tblUser tblUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblChatMessage> tblChatMessages { get; set; }
    }
}
